name: CI

on: [push, pull_request_target]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: horizonrobotics/alf:0.0.3-pytorch1.8
    # always run on push events, but only run on pull_request_target events
    # when the pull requests are from fork repositories; for pull requests
    # within the same repository, the push event is sufficient
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository)
    steps:
    - uses: actions/checkout@v1
    - name: check code style
      run: |
        ./.ci-cd/build.sh check_style
    - name: run unittest
      run: |
        PYTHONPATH=`pwd` ./.ci-cd/build.sh test
